apiVersion: v1
kind: ServiceAccount
metadata:
  name: andersoni-example
  namespace: andersoni-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: andersoni-leader-election
  namespace: andersoni-example
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: andersoni-leader-election
  namespace: andersoni-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: andersoni-leader-election
subjects:
  - kind: ServiceAccount
    name: andersoni-example
    namespace: andersoni-example
