apiVersion: v1
kind: Service
metadata:
  name: andersoni-example
  namespace: andersoni-example
spec:
  type: NodePort
  selector:
    app: andersoni-example
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
